[project]
name = "orc-konter-agent-to-1c"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.3",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
    "structlog>=25.5.0",
]
